### PR TITLE
initial work on porting yara stuff to celery

### PR DESCRIPTION
**Pull request by mutantmonkey**
I did some reorganization of the base tree in addition to porting the
YARA stuff to Celery. Historical searches have been removed for now, but
new files are now scanned using rules from the database.

### CODE REVIEW

**Comment by mutantmonkey** [comment]
Looks like there are going to be problems with yara-python and pip. I'll remove it from requirements.txt.

**Comment by mutantmonkey** [comment]
Test cases are going to require some reworking, it looks like.

**Comment by andy11** [comment]
Thanks again! I'll merge & tweak the Travis CI tests to work with this.

**Comment by andy11** [comment]
In the future, can you request to merge into andy11:dev? It made no difference this time, but sometimes it might.

**Pull request merged**
